version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    networks:
      - experiment
    ports:
      - 18081:8080
    volumes:
      - ./jenkins:/var/jenkins_home
      # Not needed - you can use the "master" agent.
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/local/bin/docker

  jenkins2:
    image: jenkins/jenkins:lts
    privileged: true
    networks:
      - experiment
    ports:
      - 18082:8080
    volumes:
      - ./jenkins2:/var/jenkins_home
      # Not needed - you can use the "master" agent.
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/local/bin/docker

  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - db
    networks:
      - experiment
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/temp:/opt/sonarqube/temp

  db:
    image: postgres
    networks:
      - experiment
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data

  shields:
    image: shieldsio/shields:next
    depends_on:
      - sonarqube
      - jenkins
    networks:
      - experiment
    ports:
      - 80:80
    # Documentation states you can use custom port - in practice you can't, because the links will point to :80 and will
    # be broken. Therefore port 80.
    # https://github.com/badges/shields/blob/master/doc/self-hosting.md#start-the-server
    command: node server 80
    volumes:
      - ./shields.local.yml:/usr/src/app/config/local.yml

networks:
  experiment:
    driver: bridge

